<style type="text/css">
  
 #row_tab1_general_shop_id  
.scope-label{
display:none;
}
 #row_tab1_general_customer_tracking 
.scope-label{
display:none;
}
 #row_tab1_general_product_listing 
.scope-label{
display:none;
}
 #row_tab1_general_shopping_cart 
.scope-label{
display:none;
}
 #row_tab1_general_wishlist_tracking  
.scope-label{
display:none;
}
 #row_tab1_general_checkout_process_tracking 
.scope-label{
display:none;
}
 #row_tab1_general_checkout_finalized  
.scope-label{
display:none;
}
 #row_tab1_general_product  
.scope-label{
display:none;
}
 #row_tab1_general_other_content 
.scope-label{
display:none;
}

</style>

<?php 
$shop_id = Mage::getStoreConfig('tab1/general/shop_id');
$customer_tracking = Mage::getStoreConfig('tab1/general/customer_tracking');
$product = Mage::getStoreConfig('tab1/general/product');
$product_listing = Mage::getStoreConfig('tab1/general/product_listing');
$shopping_cart = Mage::getStoreConfig('tab1/general/shopping_cart');
$wishlist_tracking = Mage::getStoreConfig('tab1/general/wishlist_tracking');
$checkout_process_tracking = Mage::getStoreConfig('tab1/general/checkout_process_tracking');
$checkout_finalized = Mage::getStoreConfig('tab1/general/checkout_finalized');
$other_content = Mage::getStoreConfig('tab1/general/other_content');
if($shop_id==''&& $customer_tracking==''&& $product=='' && $product_listing==''&& $shopping_cart==''&& $wishlist_tracking==''&& $checkout_finalized=='' && $other_content==''){

$config = array(
      array(
        'path' => 'tab1/general/customer_tracking',
        'value' => '1',
    ),
      array(
        'path' => 'tab1/general/product',
        'value' => '1',
    ),
        array(
        'path' => 'tab1/general/product_listing',
        'value' => '1',
    ),
          array(
        'path' => 'tab1/general/shopping_cart',
        'value' => '1',
    ),
            array(
        'path' => 'tab1/general/wishlist_tracking',
        'value' => '1',
    ),
             array(
        'path' => 'tab1/general/checkout_finalized',
        'value' => '1',
    ),
             array(
        'path' => 'tab1/general/other_content',
        'value' => '1',
    ),
);

foreach ($config as $item) {
  $setup = new Mage_Core_Model_Config();
  $setup->saveConfig($item['path'], $item['value'], 'default', 0);
}




 }